rabbit:
  image: rabbitmq:3-management
  ports:
    - "8080:15672"

link-extractor:
  build: ./link-extractor
  volumes:
    - ./link-extractor:/home/dev
  ports:
    - "3000:3000"
  links:
    - rabbit

link-visit-tracker:
  build: ./link-visit-tracker
  volumes:
    - ./link-visit-tracker:/home/dev
