rabbit:
  image: rabbitmq:3-management
  ports:
    - "8080:15672"

link-extractor:
  build: ./link-extractor
  volumes:
    - ./link-extractor:/home/dev
  ports:
    - "3000:3000"

ui:
  build: ./ui
  volumes:
    - ./ui:/home/dev
  ports:
    - "3001:3001"
