rabbit:
  image: rabbitmq:3-management
  ports:
    - "8080:15672"

link-extractor:
  build: ./link-extractor
  volumes:
    - ./link-extractor:/home/dev
  ports:
    - "3000:3000"
  environment:
    EXCHANGE: linkExchange
    EXCHANGE_TYPE: topic
    OUTBOUND_QUEUE: linkExtracted
  links:
    - rabbit

link-visit-tracker:
  build: ./link-visit-tracker
  volumes:
    - ./link-visit-tracker:/home/dev
  environment:
    EXCHANGE: linkExchange
    EXCHANGE_TYPE: topic
    INBOUND_QUEUE: linkExtracted
    OUTBOUND_QUEUE: linkUnvisited
    VISITED_SET_NAME: visited_urls
  links:
    - rabbit
    - redis

link-classifier:
  build: ./link-classifier
  volumes:
    - ./link-classifier:/home/dev
  environment:
    EXCHANGE: linkExchange
  links:
    - rabbit

redis:
  image: redis:2.8
